import { Component } from '@angular/core';

@Component({
  selector: 'page-flora',
  templateUrl: 'flora.html'
})
export class Flora {

  public plantas: Array<any>;

  constructor() {
    this.plantas = [];
    this.plantas.push({nome: 'Capivara', descricao: 'A capivara é uma espécie de mamífero roedor da família Caviidae e subfamília Hydrochoerinae. Ocorre por toda a América do Sul ao leste dos Andes em habitats associados a rios, lagos e pântanos. É o maior roedor do mundo, pesando até 91 kg e medindo até 1,2 m de comprimento e 60 cm de altura. A pelagem é densa, de cor avermelhada a marrom escuro. É possível distinguir os machos por conta da presença de uma glândula proeminente no focinho apesar do dimorfismo sexual não ser aparente.', fonte: 'https://pt.wikipedia.org/wiki/Capivara', imagem: 'imagens/capivara.jpg'});
    this.plantas.push({nome: 'Ratão-do-banhado', descricao: 'O ratão-do-banhado também conhecido por nutria, caxingui ou ratão-dágua, é uma espécie de roedor da família Echimyidae. Ocorre no sul da América do Sul. Pelagem marrom-avermelhada, cauda longa e grossa, revestida por escamas e pêlos ralos,vivendo em banhados, lagoas e rios. Dorme durante o dia. Alimenta-se de capim, raízes e plantas aquáticas e herbáceas, tubérculos, folhas, grãos, carne e peixe. O macho cuida dos filhotes no nascimento, protegendo e alimentando até a fêmea se recuperar.', fonte: 'https://pt.wikipedia.org/wiki/Myocastor_coypus', imagem: 'imagens/ratão-do-banhado.jpg'});
    this.plantas.push({nome: 'Jacaré-de-papo-amarelo', descricao: 'O jacaré-de-papo-amarelo é um réptil crocodiliano da família Alligatoridae e gênero Caiman. É amplamente distribuído pelo sudeste da América do Sul, ocorrendo em qualquer ecossistema associado à água nas bacias dos rios Paraná, Paraguai, Uruguai e São Francisco. Também ocorre em ecossistemas costeiros, como mangues. É um animal carnívoro que vive aproximadamente cinquenta anos. São conhecidos por este nome pois, durante a fase do acasalamento, estes animais costumam ficar com a área do papo amarelada.', fonte: 'https://pt.wikipedia.org/wiki/Jacar%C3%A9-de-papo-amarelo', imagem: 'imagens/jacaré-de-papo-amarelo.jpg'});
    this.plantas.push({nome: 'Biguá', descricao: 'O biguá também chamado corvo-marinho, cormorão, pata-dágua, biguaúna, imbiuá, mergulhão e miuá, é uma ave aquática falacrocoracídea preta, de dorso cinza. Tais aves habitam boa parte da região que vai do México à América do Sul, medindo cerca de 75 cm de comprimento e com coloração negra, saco gular amarelo e tarsos negros.', fonte: 'https://pt.wikipedia.org/wiki/Bigu%C3%A1', imagem: 'imagens/biguá.jpg'});
    this.plantas.push({nome: 'Frango dágua', descricao: 'A frango dágua mede aproximadamente 37 cm de comprimento. Apresenta um escudo facial vermelho, faixas brancas nos flancos, plumagem negra e patas amarelas. Os imaturos são castanho-escuros com abdome mais claro, sem o escudo facial vermelho. Alimenta-se de uma grande variedade de material vegetal, além de pequenos animais aquáticos. Freqüenta lagos, lagoas, canais, pântanos e também lagunas salobras.', fonte: 'https://pt.wikipedia.org/wiki/Gallinula_chloropus', imagem: 'imagens/frango-dágua.jpg'});
    this.plantas.push({nome: 'Tabarana', descricao: 'O Salminus hilarii é um peixe prateado, comumente chamado de tabarana ou tubarana, sendo encontrada na bacia do Rio São Francisco, nos rios Grande e Tietê da bacia do Rio da Prata, nos rios Tocantins e Madeira da bacia Amazônica além da Bacia do Orinoco e rios da Colômbia (Rio Magdalena) e rios do Equador.', fonte: 'https://pt.wikipedia.org/wiki/Salminus_hilarii', imagem: 'imagens/tabarana.jpg'});
    this.plantas.push({nome: 'Curimbatá', descricao: 'O curimbatá, também chamado papa-terra, curibatá, curimatá, curimatã, curimataú, curimba, curumbatá, crumatá, grumatá e grumatã, é um peixe teleósteo caraciforme da família dos caracídeos, da subfamília dos proquilodontídeos, especialmente do gênero Prochilodus. Vive em todo o território brasileiro. Alimenta-se de vegetais e de lodo. Pode ser aproveitado para aquacultura', fonte: 'https://pt.wikipedia.org/wiki/Curimbata', imagem: 'imagens/curimbatá.jpg'});
    this.plantas.push({nome: 'Cará', descricao: 'Cará (Pterophyllum) é um gênero de peixes de água doce, pertencente à família Cichlidae. Vive em cardume e alimenta-se predominantemente de pequenos crustáceos, peixes, larvas, insetos e outras matérias orgânicas. Nativos da bacia Amazônica podem chegar a 15 centímetros de comprimento e habita pequenos rios e lagos com densa vegetação aquática. As suas principais características são as suas variadas colorações, que se desenvolveram ao longo do tempo, o formato triangular do seu corpo e as suas longas barbatanas dorsal e caudal.', fonte: 'https://pt.wikipedia.org/wiki/Acar%C3%A1', imagem: 'imagens/cará.jpg'});
    this.plantas.push({nome: 'Lambari', descricao: 'Lambari é a designação vulgar de várias espécies de peixes do gênero Astyanax, da família Characidae, comum nos rios, lagoas, córregos e represas do Brasil. Seu tamanho médio é entre os 10 e os 15 centímetros de comprimento, possuindo um corpo prateado e nadadeiras com cores que variam conforme as espécies, sendo mais comuns os tons de amarelo, vermelho e preto. São peixes onívoros e a base da alimentação de diversos peixes predadores.', fonte: 'https://pt.wikipedia.org/wiki/Lambari', imagem: 'imagens/lambari.jpg'});
    this.plantas.push({nome: 'Carcará', descricao: 'Carcará ou caracará (nome científico: Caracara plancus) é uma espécie de ave de rapina da família dos falconídeos. Mede até 60 cm de altura e sua envergadura chega a 123 cm. Habita o centro e o sul de toda a América do Sul.', fonte: 'https://pt.wikipedia.org/wiki/Carcar%C3%A1', imagem: 'imagens/carcará.jpg'});
  }

}
