import { Component } from '@angular/core';

@Component({
  selector: 'page-flora',
  templateUrl: 'flora.html'
})
export class Flora {

  public plantas: Array<any>;

  constructor() {
    this.plantas = [];
    this.plantas.push({nome: 'Aroeira-salsa', descricao: 'Espécie arbórea com altura entre 4 e 8 metros e tronco com 25 a 35 cm de diâmetro, revestido por casca grossa e escamosa. Suas folhas são compostas, sem estípulas, com 9-25 folíolos linear-lanceolados a lineares, subcoreáceos, glabros, com 3-8 cm de comprimenro e de margens serreadas. As flores amareladas e pouco vistosas são reunidas em inflorescências e os frutos são drupas globosas e de coloração vermelha.', fonte: 'http://www.ibflorestas.org.br', imagem: 'imagens/aroeira-salsa.jpg'});
    this.plantas.push({nome: 'Aroeira-pimenteira', descricao: 'A Aroeira Pimenteira (Schinus terebinthifolia), é uma árvore bastante interessante para arborização urbana. Seu porte médio e a frutificação ornamental, aliados à rusticidade da planta, fazem com que ela seja uma excelente escolha para o paisagismo, prestando-se como arvoreta e cerca-viva. Ela também é indicada para reflorestamento de áreas degradas, pois é uma árvore pioneira. A pimenta-rosa, seu fruto, é muito popular na França, onde é utilizada na ornamentação e tempero de preparações culinárias. Seu sabor é levemente picante e adocicado.', fonte: 'http://ibflorestas.org.br', imagem: 'imagens/aroeira-pimenteira.jpg'});
    this.plantas.push({nome: 'Araticum', descricao: 'O araticum (nome científico Annona crassiflora) é uma planta característica do Cerrado. Ocorre, normalmente, em áreas secas e arenosas. Chega a alcançar entre quatro e oito metros de altura. De crescimento lento, costuma frutificar quando chega aos dois metros. Tem um fruto bastante conhecido e muito apreciado. Dependendo da região, leva o nome de pinha, ata, marolo, condessa, bruto, cabeça-de-negro, entre outros. O nome araticum é derivado do tupi e significa “árvore rija e dura, fruto do céu, saboroso, ou ainda fruto mole”, visto que sua polpa é branca, viscosa e mole quando maduro.', fonte: 'http://www.cerratinga.org.br/araticum/', imagem: 'imagens/araticum.jpg'});
    this.plantas.push({nome: 'Gabiroba', descricao: 'Gabiroba – Campomanesia xanthocarpa, com tamanho entre 40 a 60 centímetros, no tubete de 290 cm³, com folhas bem nutridas e rustificadas, caule lenhoso com 5 mm, raízes bem agregadas ao substrato. Folhas opostas, simplesm elípticas a obovadasm cartáceas, glabras a glabrescentes, com nervação broquidódroma e saliente na face inferior, lustrosas na face superior, de 2-3 cm de comprimento por 1-1,5 cm de largura, sustentadas por pecíolo de aproximadamente 1 cm de comprimento. Fruto baga glabra, amarela quando madura, com polpa carnosa, doce-acidulada e comestível contendo poucas sementes.', fonte: 'http://www.ibflorestas.org.br', imagem: 'imagens/gabiroba.jpg'});
    this.plantas.push({nome: 'Araçá vermelho', descricao: 'O araçazeiro, cujo fruto é o araçá, é uma árvore ou arvoreta, de copa esparsa, muitas vezes com porte arbustivo, alcançando de 6 a 9 metros de altura. Ocorre naturalmente da Bahia ao Rio Grande do Sul, na Mata Altlântica. Seu tronco é tortuoso e apresenta casca lisa, escamosa, na cor cinza a marrom avermelhada, com ramos pubescentes quando jovens. As folhas são opostas, coriáceas, glabras, simples, inteiras, com forma elíptica a oblonga, e 5 a 10 cm de comprimento. As flores são solitárias, axilares e brancas, com longos estames. O período de florescimento é longo, estendendo-se de junho a dezembro.', fonte: '', imagem: 'imagens/araçá-vermelho.jpg'});
    this.plantas.push({nome: 'Araçá amarelo', descricao: 'Espécie arbórea com altura de 3-6 metros e tronco de 15-25 cm de diâmetro. As folhas são simples, coriáceas, glabras, de 5 -10 cm de comprimento por 3 - 6 cm de largura, com pecíolo de 0,4 -1,0 cm de comprimento. As flores são de coloração amarela e os frutos são bagas globosas de coloração entre amarelo e vermelho.', fonte: 'http://www.ibflorestas.org.br', imagem: 'imagens/araçá-amarelo.jpg'});
    this.plantas.push({nome: 'Ipê', descricao: 'Árvore decídua, de crescimento rápido, com altura de 8 a 12 m, pode chegar aos 30 m no interior da mata. Ocupa na mata primária o dossel superior. As folhas são compostas com 5 folíolos grandes, como a maioria dos ipês. São coriáceas ou subcoriáceas. O frutos são capsulas septicidas grossas em uma vagem deiscente. As sementes membranáceas são dispersas por anemocoria (pelo vento).', fonte: 'https://pt.wikipedia.org/wiki/Handroanthus_impetiginosus', imagem: 'imagens/ipê.jpg'});
    this.plantas.push({nome: 'Pitanga', descricao: 'A pitanga é o fruto da pitangueira (Eugenia uniflora L.), dicotiledônea da família das mirtáceas. Tem a forma de bolinhas globosas e carnosas, de cor vermelha (a mais comum), laranja, amarela ou preta. Na mesma árvore, o fruto poderá ter desde as cores verde, amarelo e alaranjado até a cor vermelho-intenso, de acordo com o grau de maturação.', fonte: 'https://pt.wikipedia.org/wiki/Pitanga', imagem: 'imagens/pitanga.jpg'});
    this.plantas.push({nome: 'Angico', descricao: 'Angico é a designação comum a várias árvores dos gêneros Piptadenia, Parapiptadenia e Anadenanthera da sub-família Mimosoideae. Elas são nativas da América tropical, principalmente do Brasil e também são exploradas e/ou cultivadas devido à boa qualidade da sua madeira.', fonte: 'https://pt.wikipedia.org/wiki/Angico', imagem: 'imagens/angico.jpg'});
  }

}
