import { Component } from '@angular/core';

@Component({
  selector: 'page-fauna',
  templateUrl: 'fauna.html'
})
export class Fauna {

  public animais: Array<any>;

  constructor() {
    this.animais = [];
    this.animais.push({nome: 'Capivara', descricao: 'A capivara é uma espécie de mamífero roedor da família Caviidae e subfamília Hydrochoerinae. Ocorre por toda a América do Sul ao leste dos Andes em habitats associados a rios, lagos e pântanos. É o maior roedor do mundo, pesando até 91 kg e medindo até 1,2 m de comprimento e 60 cm de altura. A pelagem é densa, de cor avermelhada a marrom escuro. É possível distinguir os machos por conta da presença de uma glândula proeminente no focinho apesar do dimorfismo sexual não ser aparente.', fonte: 'https://pt.wikipedia.org/wiki/Capivara', imagem: 'imagens/capivara.jpg'});
    this.animais.push({nome: 'Ratão-do-banhado', descricao: 'O ratão-do-banhado também conhecido por nutria, caxingui ou ratão-dágua, é uma espécie de roedor da família Echimyidae. Ocorre no sul da América do Sul. Pelagem marrom-avermelhada, cauda longa e grossa, revestida por escamas e pêlos ralos,vivendo em banhados, lagoas e rios. Dorme durante o dia. Alimenta-se de capim, raízes e plantas aquáticas e herbáceas, tubérculos, folhas, grãos, carne e peixe. O macho cuida dos filhotes no nascimento, protegendo e alimentando até a fêmea se recuperar.', fonte: 'https://pt.wikipedia.org/wiki/Myocastor_coypus', imagem: 'imagens/ratão-do-banhado.jpg'});
    this.animais.push({nome: 'Jacaré-de-papo-amarelo', descricao: 'O jacaré-de-papo-amarelo é um réptil crocodiliano da família Alligatoridae e gênero Caiman. É amplamente distribuído pelo sudeste da América do Sul, ocorrendo em qualquer ecossistema associado à água nas bacias dos rios Paraná, Paraguai, Uruguai e São Francisco. Também ocorre em ecossistemas costeiros, como mangues. É um animal carnívoro que vive aproximadamente cinquenta anos. São conhecidos por este nome pois, durante a fase do acasalamento, estes animais costumam ficar com a área do papo amarelada.', fonte: 'https://pt.wikipedia.org/wiki/Jacar%C3%A9-de-papo-amarelo', imagem: 'imagens/jacaré-de-papo-amarelo.jpg'});
    this.animais.push({nome: 'Biguá', descricao: 'O biguá também chamado corvo-marinho, cormorão, pata-dágua, biguaúna, imbiuá, mergulhão e miuá, é uma ave aquática falacrocoracídea preta, de dorso cinza. Tais aves habitam boa parte da região que vai do México à América do Sul, medindo cerca de 75 cm de comprimento e com coloração negra, saco gular amarelo e tarsos negros.', fonte: 'https://pt.wikipedia.org/wiki/Bigu%C3%A1', imagem: 'imagens/biguá.jpg'});
    this.animais.push({nome: 'Frango dágua', descricao: 'A frango dágua mede aproximadamente 37 cm de comprimento. Apresenta um escudo facial vermelho, faixas brancas nos flancos, plumagem negra e patas amarelas. Os imaturos são castanho-escuros com abdome mais claro, sem o escudo facial vermelho. Alimenta-se de uma grande variedade de material vegetal, além de pequenos animais aquáticos. Freqüenta lagos, lagoas, canais, pântanos e também lagunas salobras.', fonte: 'https://pt.wikipedia.org/wiki/Gallinula_chloropus', imagem: 'imagens/frango-dágua.jpg'});
    this.animais.push({nome: 'Tabarana', descricao: 'O Salminus hilarii é um peixe prateado, comumente chamado de tabarana ou tubarana, sendo encontrada na bacia do Rio São Francisco, nos rios Grande e Tietê da bacia do Rio da Prata, nos rios Tocantins e Madeira da bacia Amazônica além da Bacia do Orinoco e rios da Colômbia (Rio Magdalena) e rios do Equador.', fonte: 'https://pt.wikipedia.org/wiki/Salminus_hilarii', imagem: 'imagens/tabarana.jpg'});
    this.animais.push({nome: 'Curimbatá', descricao: 'O curimbatá, também chamado papa-terra, curibatá, curimatá, curimatã, curimataú, curimba, curumbatá, crumatá, grumatá e grumatã, é um peixe teleósteo caraciforme da família dos caracídeos, da subfamília dos proquilodontídeos, especialmente do gênero Prochilodus. Vive em todo o território brasileiro. Alimenta-se de vegetais e de lodo. Pode ser aproveitado para aquacultura', fonte: 'https://pt.wikipedia.org/wiki/Curimbata', imagem: 'imagens/curimbatá.jpg'});
    this.animais.push({nome: 'Cará', descricao: 'Cará (Pterophyllum) é um gênero de peixes de água doce, pertencente à família Cichlidae. Vive em cardume e alimenta-se predominantemente de pequenos crustáceos, peixes, larvas, insetos e outras matérias orgânicas. Nativos da bacia Amazônica podem chegar a 15 centímetros de comprimento e habita pequenos rios e lagos com densa vegetação aquática. As suas principais características são as suas variadas colorações, que se desenvolveram ao longo do tempo, o formato triangular do seu corpo e as suas longas barbatanas dorsal e caudal.', fonte: 'https://pt.wikipedia.org/wiki/Acar%C3%A1', imagem: 'imagens/cará.jpg'});
    this.animais.push({nome: 'Lambari', descricao: 'Lambari é a designação vulgar de várias espécies de peixes do gênero Astyanax, da família Characidae, comum nos rios, lagoas, córregos e represas do Brasil. Seu tamanho médio é entre os 10 e os 15 centímetros de comprimento, possuindo um corpo prateado e nadadeiras com cores que variam conforme as espécies, sendo mais comuns os tons de amarelo, vermelho e preto. São peixes onívoros e a base da alimentação de diversos peixes predadores.', fonte: 'https://pt.wikipedia.org/wiki/Lambari', imagem: 'imagens/lambari.jpg'});
    this.animais.push({nome: 'Carcará', descricao: 'Carcará ou caracará (nome científico: Caracara plancus) é uma espécie de ave de rapina da família dos falconídeos. Mede até 60 cm de altura e sua envergadura chega a 123 cm. Habita o centro e o sul de toda a América do Sul.', fonte: 'https://pt.wikipedia.org/wiki/Carcar%C3%A1', imagem: 'imagens/carcará.jpg'});
    this.animais.push({nome: 'Socó-dorminhoco', descricao: 'O savacu, goraz ou socó-dorminhoco (Nycticorax nycticorax) é uma ave pelecaniforme da família dos ardeídeos, bastante comum em quase todo o continente americano e em parte da Europa. Tais aves medem cerca de 60 cm de comprimento, possuindo tanto o alto da cabeça quanto o dorso negros, asas cinzentas, fronte, partes inferiores e longas penas nucais brancas', fonte: 'https://pt.wikipedia.org/wiki/Savacu', imagem: 'imagens/socó-dorminhoco.jpg'});
    this.animais.push({nome: 'Cágado-de-barbicha', descricao: 'A espécie distribui-se pela América Latina sendo encontrada na Bolívia, Venezuela, Colômbia, Peru, Equador, Guiana, Paraguai, Argentina e Brasil. Habita lagos, lagoas, pântanos e rios de correnteza fraca como trechos da Bacia Amazônica, rio Paraná e São Francisco. O casco tem coloração dorsal cinza-esverdeada e ventral avermelhada com manchas pretas, ele é largo e achatado dorsiventralmente. Ótimo nadador, os dedos são ligados por membranas que auxiliam na natação.', fonte: 'http://www.aprenda.bio.br/portal/?p=3880', imagem: 'imagens/cágado-de-barbicha.jpg'});
    this.animais.push({nome: 'Irerê', descricao: 'A Dendrocygna viduata é uma espécie de marreca encontrada na África tropical, nas Antilhas e na América do Sul. Tais aves medem cerca de 44 centímetros de comprimento e têm plumagem em máscara, calça e luva brancas, nuca e asas negras, flancos listrados, bicos e pés plúmbeos. A ave, que comumente é chamada irerê mas também é conhecido como paturi, marrecão (Rio Grande do Sul) e siriri ou marreca-viúva (Paraíba).', fonte: 'https://pt.wikipedia.org/wiki/Irer%C3%AA', imagem: 'imagens/irerê.jpg'});
    this.animais.push({nome: 'Lambari de rabo vermelho', descricao: 'Da família Characidae (Caracídeos), o Lambari de rabo vermelho tem origem na América do Norte, Central e do Sul. Encontrado desde o México até Argentina. Quando adulto pode chegar até 17 cm e possui uma expectativa de Vida de 5 anos.', fonte: 'http://www.aquarismopaulista.com/lambari-astyanax-fasciatus/', imagem: 'imagens/lambari-de-rabo-vermelho.jpg'});
    this.animais.push({nome: 'Corujinha-buraqueira', descricao: 'A coruja-buraqueira (Athene cunicularia, anteriormente Speotyto cunicularia), também chamada caburé-do-campo, coruja-do-campo, coruja-mineira, corujinha-buraqueira, corujinha-do-buraco, guedé, urucuera, urucureia e urucuriá, recebe o nome de "buraqueira" por viver em buracos cavados no solo. Embora seja capaz de cavar seu próprio buraco, prefere os buracos abandonados de outros animais, como os dos tatus. É uma coruja terrícola e de hábitos diurnos, embora tenda a evitar o calor do meio-dia. Ocorre do Canadá à Terra do Fogo, bem como em quase todo o Brasil, mas com a exceção da Amazônia. Tais aves chegam a medir até 27 centímetros de comprimento. Costumam viver em campos, pastos, restingas, desertos, planícies, praias e aeroportos.', fonte: 'https://pt.wikipedia.org/wiki/Coruja-buraqueira', imagem: 'imagens/corujinha-buraqueira.jpg'});
  }


}
